In [51]:
import numpy as np
import pandas as pd
import matplotlib .pyplot as plt
import seaborn as sns

In [52]:
df=pd.read_csv("/content/covid_toy.csv")

In [53]:
df

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
1,27,Male,100.0,Mild,Delhi,Yes
2,42,Male,101.0,Mild,Delhi,No
3,31,Female,98.0,Mild,Kolkata,No
4,65,Female,101.0,Mild,Mumbai,No
...,...,...,...,...,...,...
95,12,Female,104.0,Mild,Bangalore,No
96,51,Female,101.0,Strong,Kolkata,Yes
97,20,Female,101.0,Mild,Bangalore,No
98,5,Female,98.0,Strong,Mumbai,No


In [54]:
df.describe()

,age,fever
count,100.000000,90.000000
mean,44.220000,100.844444
std,24.878931,2.054926
min,5.000000,98.000000
25%,20.000000,99.000000
50%,45.000000,101.000000
75%,66.500000,102.750000
max,84.000000,104.000000


In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   age        100 non-null    int64  
 1   gender     100 non-null    object 
 2   fever      90 non-null     float64
 3   cough      100 non-null    object 
 4   city       100 non-null    object 
 5   has_covid  100 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB


In [56]:
df.shape

(100, 6)

In [57]:
df.isnull().sum()

,0
age,0
gender,0
fever,10
cough,0
city,0
has_covid,0


In [58]:
from sklearn.model_selection import train_test_split

In [59]:
X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=["has_covid"]),df["has_covid"],test_size=0.2)

In [60]:
X_train

,age,gender,fever,cough,city
39,50,Female,103.0,Mild,Kolkata
36,38,Female,101.0,Mild,Bangalore
46,19,Female,101.0,Mild,Mumbai
48,66,Male,99.0,Strong,Bangalore
1,27,Male,100.0,Mild,Delhi
...,...,...,...,...,...
7,20,Female,NaN,Strong,Mumbai
23,80,Female,98.0,Mild,Delhi
5,84,Female,NaN,Mild,Bangalore
3,31,Female,98.0,Mild,Kolkata


In [61]:
y_train

,has_covid
39,No
36,No
46,No
48,No
1,Yes
...,...
7,Yes
23,Yes
5,Yes
3,No


In [62]:
from sklearn.impute import SimpleImputer

In [63]:
SI=SimpleImputer()

In [64]:
X_train_fever=SI.fit_transform(X_train[['fever']])
X_train_fever

array([[103.        ],
       [101.        ],
       [101.        ],
       [ 99.        ],
       [100.        ],
       [102.        ],
       [102.        ],
       [104.        ],
       [ 98.        ],
       [ 99.        ],
       [101.        ],
       [100.        ],
       [ 99.        ],
       [104.        ],
       [ 98.        ],
       [104.        ],
       [ 98.        ],
       [104.        ],
       [102.        ],
       [100.        ],
       [100.87671233],
       [100.        ],
       [102.        ],
       [101.        ],
       [ 99.        ],
       [ 98.        ],
       [104.        ],
       [100.87671233],
       [101.        ],
       [101.        ],
       [ 98.        ],
       [100.87671233],
       [ 98.        ],
       [100.87671233],
       [104.        ],
       [ 99.        ],
       [102.        ],
       [ 98.        ],
       [101.        ],
       [104.        ],
       [101.        ],
       [103.        ],
       [100.        ],
       [104

In [65]:
X_train_fever.shape

(80, 1)

In [66]:
from sklearn.preprocessing import OrdinalEncoder

In [67]:
oe=OrdinalEncoder()

In [68]:
oe = OrdinalEncoder(categories=[['Mild','Strong']])

In [69]:
X_train_cough=oe.fit_transform(X_train[['cough']])
X_train_cough

array([[0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],

In [70]:
from sklearn.preprocessing import OneHotEncoder

In [71]:
ohe=OneHotEncoder( sparse_output=False)

In [72]:
ohe.fit_transform(X_train[['gender','city']])

array([[1., 0., 0., 0., 1., 0.],
       [1., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1., 0.],
       [1., 0., 1., 0., 0., 0.],
       [1., 0., 0., 1., 0., 0.],
       [0., 1., 1., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 1., 0.],
       [1., 0., 1., 0., 0., 0.],
       [1., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1., 0.],
       [0., 1., 0., 1., 0., 0.],
       [1., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0.],
       [0., 1., 1., 0., 0., 0.],
       [0.

In [73]:
from sklearn.compose import ColumnTransformer

In [96]:
from sklearn.preprocessing import StandardScaler

Transformer = ColumnTransformer(
    transformers=[
        ('transfer_1',SimpleImputer(),['fever']),
        ('transfer_2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
        ('transfer_3',OneHotEncoder(),['gender','city'])
    ],
    remainder='passthrough'


)
Transformer

ColumnTransformer(remainder='passthrough',
                  transformers=[('transfer_1', SimpleImputer(), ['fever']),
                                ('transfer_2',
                                 OrdinalEncoder(categories=[['Mild',
                                                             'Strong']]),
                                 ['cough']),
                                ('transfer_3', OneHotEncoder(),
                                 ['gender', 'city'])])

In [98]:
X_train_Transform = Transformer.fit_transform(X_train)

print(X_train_Transform)

[[103.           0.           1.           0.           0.
    0.           1.           0.          50.        ]
 [101.           0.           1.           0.           1.
    0.           0.           0.          38.        ]
 [101.           0.           1.           0.           0.
    0.           0.           1.          19.        ]
 [ 99.           1.           0.           1.           1.
    0.           0.           0.          66.        ]
 [100.           0.           0.           1.           0.
    1.           0.           0.          27.        ]
 [102.           1.           1.           0.           0.
    0.           1.           0.          82.        ]
 [102.           1.           1.           0.           1.
    0.           0.           0.          24.        ]
 [104.           1.           1.           0.           0.
    1.           0.           0.          75.        ]
 [ 98.           1.           0.           1.           1.
    0.           0.          